config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth, :avatar) }
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy
  ]
  before_action :authenticate_user!
  
  def index
    @posts = Post.all.order("created_at DESC")
  end
  
  def new
      @post = Post.new
  end
  
  def create
      @post = Post.new(post_params)
      if  @post.save
          redirect_to @post
     else
          render new
      end
  end
  
  def show
    
  end
  
  def edit
     
  end
  
  def destroy
    @post.destroy
    redirect_to root_path
  end
  
  
  def update
     if @post.update(post_params)
       redirect_to @post
     else
       render 'edit'
     end
  end
  
  def find_post
    @post = Post.find(params[:id])
  end
  
  def post_params
    params.require(:post).permit(:title, :body, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <p class="navbar-text pull-right">
<% if user_signed_in? %>
 
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <span class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></span>
  
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
     <%= f.label :title %> <br>
     <%= f.text_field :title %> <br>
     <br>
      <%= f.label :body %> <br>
     <%= f.text_field :body %> <br>
     <br>
     <%= f.label :image %> <br>
     <%= f.file_field :image %> <br>
     <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>edit</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <h2> <%= post.title %> </h2>
    <div> <%= truncate(post.body, :length => 35) %></div>
    <%= link_to "Read post", post %>
    
    
<% end %>

app/views/posts/new.html.erb
<h1>new</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %> </h1>
<div>
    <%= @post.body %>
</div>
<%= image_tag @post.image.url(:medium) %>
<%= link_to "edit", edit_post_path(@post) %>
<%= link_to "delete", post_path(@post), method:  :delete, data: { confirm: "Are you sure?" } %>
<%= link_to "See the Posts", posts_path(@post) %>